// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhT4G2tZUQdzbrTMsJMtPyVY2rxdR-Vhc',
    appId: '1:162994972396:web:99bd3cca2224e17a0aa7c9',
    messagingSenderId: '162994972396',
    projectId: 'ecommerceapp-9fabd',
    authDomain: 'ecommerceapp-9fabd.firebaseapp.com',
    storageBucket: 'ecommerceapp-9fabd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSwsqbwKiDOddb3FprJYkoC59lqlhrWnk',
    appId: '1:162994972396:android:da20cf7388815c910aa7c9',
    messagingSenderId: '162994972396',
    projectId: 'ecommerceapp-9fabd',
    storageBucket: 'ecommerceapp-9fabd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC59qTMy7IpWPE8fRrMr9XhIZxXGg21-o0',
    appId: '1:162994972396:ios:c53a5f68232d4e4e0aa7c9',
    messagingSenderId: '162994972396',
    projectId: 'ecommerceapp-9fabd',
    storageBucket: 'ecommerceapp-9fabd.appspot.com',
    androidClientId: '162994972396-ma5f33bjv2lmbd9ds34s473ijta2g8mo.apps.googleusercontent.com',
    iosClientId: '162994972396-ot1aud8gnmh4m1742vr0jm8ok8vig67v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC59qTMy7IpWPE8fRrMr9XhIZxXGg21-o0',
    appId: '1:162994972396:ios:dd7d531ace6c0a860aa7c9',
    messagingSenderId: '162994972396',
    projectId: 'ecommerceapp-9fabd',
    storageBucket: 'ecommerceapp-9fabd.appspot.com',
    androidClientId: '162994972396-ma5f33bjv2lmbd9ds34s473ijta2g8mo.apps.googleusercontent.com',
    iosClientId: '162994972396-kg8b3dab7n8eldp4vmd9pq2id4v2qpt7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject.RunnerTests',
  );
}
